name: build and upload

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: vernemq/vmq-plugin-bundler
            options: |
                -v ${{ github.workspace }}:/vmq-jwt-auth-plugin
                -v ${{ github.workspace }}/dist:/bundler
                -v ${{ github.workspace }}/rebar-build.sh:/run.sh
                -e VERNEMQ_VERSION=1.12.6.2
                -e BUNDLER_CONFIG=/vmq-jwt-auth-plugin/rebar.config
            run: /run.sh
      - name: Upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: vmq-jwt-auth-plugin.tar.gz
          path: ${{ github.workspace }}/dist
          if-no-files-found: error