name: build and upload

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: vernemq/vmq-plugin-bundler:latest
      options: --user root
      env:
        VERNEMQ_VERSION: 1.12.6.2
        BUNDLER_CONFIG: ./rebar.config
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run Build Script
        run: ./rebar-build.sh
        shell: bash
        working-directory: $GITHUB_WORKSPACE

      - name: Upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: vmq-jwt-auth-plugin.tar.gz
          path: ./bundler
          if-no-files-found: error